# Generated by Django 3.2.5 on 2021-07-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_hascomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hascomment',
            field=models.BooleanField(default=True),
        ),
    ]
