# Generated by Django 3.2.5 on 2021-07-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_hascomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='related_post',
            field=models.ManyToManyField(blank=True, null=True, related_name='related_post', to='blog.post'),
        ),
    ]
