# Generated by Django 3.2.5 on 2021-07-26 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210727_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='related_post',
        ),
        migrations.AddField(
            model_name='comment',
            name='related_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_post', to='blog.post'),
        ),
    ]
