# Generated by Django 3.2.5 on 2021-07-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20210727_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='amberuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='profiles'),
        ),
    ]
