# Generated by Django 3.2.5 on 2021-07-27 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_temperoryaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amberuser',
            name='bio',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
