# Generated by Django 3.2.5 on 2021-07-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_amberuser_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='resetpassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=256, null=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='temperoryaccount',
            name='isactivenow',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
