# Generated by Django 3.2.5 on 2021-07-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20210727_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='resetpassword',
            name='linkuseronce',
            field=models.BooleanField(default=False),
        ),
    ]
